### ISSUE TITLE
Keyboard shortcut?

### ISSUE THREAD

**Issue by Wisdawn** [shirsig/Cleanup#14]
Thank you very much for working on this addon.

I understand how to place the addon button just on top of a bar button or so, but is there any way currently to give the addon button a keybinding or keyboard shortcut?

I'm mostly a keyboard user so it'd a huge quality-of-life improvement for me.

Thank you.

**Comment by shirsig** [comment]
Well, Cleanup only provides the buttons for SortBags which provides a lua api anyway.
You can just put **/run SortBags()** or **/run SortBankBags()** in a macro and assign it to a key.

**Comment by Wisdawn** [comment]
Perfect!

I literally came back to say, alternatively, is there a command that I can macro? xD

Thank you!
