### ISSUE TITLE
Error message :(

### ISSUE THREAD

**Issue by RetroDisko** [shirsig/Cleanup#19]
Hi Shirsig, I’ve tried to use this addon but every time I load it I would always get an error message saying along the lines of “attempt to call global ‘clean up’ (a nil value)”. I am using 1.12.1 and also have the sortbag addon too. Thank you in advance!!

**Comment by shirsig** [comment]
Hey. The vanilla (1.12.1) versions are in different repos: https://github.com/shirsig/Cleanup-vanilla, https://github.com/shirsig/SortBags-vanilla

**Comment by shirsig** [comment]
Hey. The vanilla (1.12.1) versions are in different repos: https://github.com/shirsig/Cleanup-vanilla, https://github.com/shirsig/SortBags-vanilla
