### ISSUE TITLE
Make the Button Appear in the Default Bags

### ISSUE THREAD

**Issue by phendrome** [shirsig/Cleanup#2]
When I use the command /cleanupbags the whole screen becomes yellow and I get to choose where the button should be on my screen - and it's there **ALL** the time. Annoying, as hell.

I'd prefer just having them in the primary bag, just like on retail right now.

Is it possible to fix this?

Cheers,
phendrome

**Comment by shirsig** [comment]
The yellow highlights the frame where the button will be placed. With the mousewheel you can scroll through the frames. It's all described in the readme.

**Comment by phendrome** [comment]
Thank you, I must've missed it. Well done btw, greatly appreciated with the time and effort you put into developing these legacy addons.
