### ISSUE TITLE
Cleanup no longer works as of the Ulduar patch in _Wrath of the Lich King Classic_

### ISSUE THREAD

**Issue by nerolite** [shirsig/Cleanup#20]
Cleanup no longer works as of the Ulduar patch in _Wrath of the Lich King Classic_. The Cleanup icon is not visible and the addon throws an error.
- Ulduar patch: Version 3.4.1 Build 47612, released on January 17, 2023

Error:
```

Message: bad argument #2 to '?' (Usage: self:SetParent([parent]))
Time: Wed Feb  8 00:43:00 2023
Count: 5034
Stack: bad argument #2 to '?' (Usage: self:SetParent([parent]))
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetParent'
[string "@Interface/AddOns/Cleanup/Cleanup.lua"]:89: in function `UpdateButton'
[string "@Interface/AddOns/Cleanup/Cleanup.lua"]:69: in function <Interface/AddOns/Cleanup/Cleanup.lua:67>

Locals: (*temporary) = 0.008000
(*temporary) = <function> defined =[C]:-1

```

Is there any way to address this? Is there a simple code change that can be made to ensure Cleanup still works?

**Comment by shirsig** [comment]
I didn't know it ever worked even in TBC, I never updated it after classic.
However, you don't really need it anyway, you can just run SortBags directly with a macro **/run SortBags()** and put it on action button.

**Comment by nerolite** [comment]
Yeah, it has been working great until recently. However, the Ulduar patch (3.4.1) in WotLK Classic brought with it the code changes from Dragonflight (10.0.0), which should be the cause of the error.

**Troubleshooting**
I thought I was on to something with the change of `"UIParent"` -> to `UIParent` as an argument for SetParent, but I could not locate any such string argument in the LUA code for Cleanup. 

> [Patch 10.0.0](https://wowpedia.fandom.com/wiki/Patch_10.0.0/API_changes) (2022-10-25): No longer supports accepting a string argument, e.g. "UIParent" instead of UIParent. No longer requires an explicit nil to remove the parent. [Source](https://wowpedia.fandom.com/wiki/API_ScriptRegion_SetParent)

**Suggestion feedback**
I am sort of strapped for actionbar space so I much preferred having the Cleanup button, rather than macros for sorting the bag and bank. I much appreciate the input though and it will go with this solution if I cannot get the Cleanup button to appear.

**Comment by shirsig** [comment]
I've fixed it and also created a wotlk version on curse.

**Comment by nerolite** [comment]
Thanks for taking a look into it, it is really appreciated! Very glad to have this functionality back.
