### ISSUE TITLE
 /cleanupbags command doesn't exist

### ISSUE THREAD

**Issue by Evyn97** [shirsig/Cleanup#21]
and there's no button (I have sortbags)

**Comment by shirsig** [comment]
Perhaps it didn't load because it was out of date after the recent update? I've updated all the client versions now.

**Comment by Evyn97** [comment]
still experiencing the same issue on Turtle WoW :(

**Comment by shirsig** [comment]
This is the wrong repo for private servers, the right one is here: https://github.com/shirsig/Cleanup-vanilla (same will be the case for the SortBags dependency)
