### ISSUE TITLE
Compatibility issue with Luna Unit Frames

### ISSUE THREAD

**Issue by OskarOskar** [shirsig/Cleanup#3]
When trying to place the button with /cleanupbags I get this error message:
![image](https://cloud.githubusercontent.com/assets/6757518/22614882/3d73ccb2-ea89-11e6-805c-dad73fec801d.png)
This only happens when Luna UF is enabled, so a workaround is just to disable Luna, place the button and then re-enable it afterwards.

**Comment by shirsig** [comment]
That's a bug in luna (and been fixed for a while afaik)

**Comment by OskarOskar** [comment]
Oh whoops you're right, I updated to the newest Luna version and that fixed it.
