### ISSUE TITLE
How do I reverse the sorting?

### ISSUE THREAD

**Issue by khay85** [shirsig/Cleanup#7]
I obviously play differently than you do, and I much prefer more permanent or longer duration items on top instead of bottom.

Is there a simple way to reverse the sorting?

**Comment by shirsig** [comment]
Well, you can do **/script SetSortBagsRightToLeft(true)**, but that will not only reverse the item order but also place them on the opposite end of your bags.

If you just want to change the sort order you'll have to change the code in your local version of https://github.com/shirsig/SortBags/blob/master/SortBags.lua, namely on line 352 you have to change **LT(itemSortKeys[a], itemSortKeys[b])** into **not LT(itemSortKeys[a], itemSortKeys[b])**
